### ISSUE TITLE
Can't get timer to start

### ISSUE THREAD

**Issue by PTRPlay** [yassinedoghri/react-timer-machine#8]
Trying to install it on top of fresh create-react-app project.
Copy pasted the example code and it just shows 10 which is timeStart.
It never changes, callbacks onStart etc are never called.

**Comment by yassinedoghri** [comment]
Thanks for your comment! I've fixed it and released v1.0.2

**Comment by yassinedoghri** [comment]
> Trying to install it on top of fresh create-react-app project.
> Copy pasted the example code and it just shows 10 which is timeStart.
> It never changes, callbacks onStart etc are never called.

Thanks for your comment! I've fixed it and released v1.0.2
